### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by araskachoi** [ChainSafe/chainlink-cosmos#100]
Write tests for the following:
`x/keeper`:
- [x] grpc_query_test.go
- [x] keeper_test.go
- [x] --msg_server_test.go--
- [x] querier_test.go
- [x] util_test.go

`x/types`:
- [x] codec_test.go
- [x] coin_test.go
- [x] genesis_test.go
- [x] msg_test.go
- [x] querier_test.go
- [x] types_test.go

**Comment by araskachoi** [comment]
TODO: update
